version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/coderspace-todo-task
    environment:
      - DATABASE_URL=sqlite:////coderspace-todo-task/sqlite.db

